# 全局配置 globalConfig
globalConfig:
  # 执行完是否打开文件
  isOpen: true
  # 输出路径 注意：windows文件路径复制时斜杠要么"/"或者是"\\",直接复制过来是"\",这样是有问题的，请主动改成"/"或者是"\\"
#  outPutDir: D:\
  # 是否覆盖文件
  fileOverride: true
  # 是否关闭输出流 true-开启输出流，false-关闭输出流，主要用途查看参数，又不想生成文件
  closeWriter: false
  # 根包位置
  parent: top.ticho.module
  # tables: table_name1,table_name2
  tables: sys_dict
  # 表前缀去除。可批量，逗号隔开
  tablePrefixs: sys
  # 主键名称，如id,如果实际表中有主键id，这个属性会被替代
  keyName: id
  # 模板模块
  module: test
  # 时间类型  ONLY_DATE - java.util.Date || SQL_PACK - java.sql.Date、java.sql.Time、java.sql.Timestamp || TIME_PACK - java.time.LocalDate、java.time.LocalTime
  dateType: TIME_PACK
# 数据源配置 dataConfig 目前仅支持myql
dataConfig:
  url: jdbc:mysql://127.0.0.1:3306/fog_dev?useUnicode=true&characterEncoding=UTF-8&useSSL=true&serverTimezone=GMT%2B8
  driverName: com.mysql.cj.jdbc.Driver
  username: root
  password: 123456

# 通用配置
common:
  # 作者
  author: zhajianjun
  # 日期，默认当前时间，可不填
  date:
  # 开启lombok
  enableLombok: true
  # 开启swagger
  enableSwagger: true
  # 开启mybatis缓存
  enableMybatisCache: false
  # 开启mybatisplus
  enableMybatisPlus: true
  # 模板参数文件是否生成
  createJsonFile: true
  # 项目名称
  project:

# 模板配置 template
# 相对包路径
template:
  entity:
    pkgOrPath: entity
    suffix:
  mapper:
    pkgOrPath: mapper
    suffix: Mapper
  mapperXml:
    pkgOrPath: resources/mapper/
    suffix: Mapper
  service:
    pkgOrPath: service
    suffix: Service
  serviceImpl:
    pkgOrPath: service.impl
    suffix: ServiceImpl
  controller:
    pkgOrPath: controller
    suffix: Controller
  vueApi:
    pkgOrPath: resources/static/js
    suffix:
  vueForm:
    pkgOrPath: resources/static/vue
    suffix: